"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = """
$character\
$directory\
$git_branch\
$git_status\
"""

right_format = """
$cmd_duration\
$kubernetes\
$aws\
$azure\
$gcloud\
$nix_shell\
$python\
$battery\
$jobs\
"""

### Left Prompt ###
[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
format = '[$read_only]($read_only_style)[$path]($style) '
truncation_length = 1

[git_branch]
symbol = 'git'
format = '[$symbol:\([$branch](bold red)\)](bold blue) '
truncation_length = 16

[git_status]
format = '([$all_status$ahead_behind](bold yellow) )'
use_git_executable = true

### Right Prompt ###
[cmd_duration]
format = '\[[⏱ $duration]($style)\]'

[battery]
format = '\[[$symbol$percentage]($style)\]'
[[battery.display]]
threshold = 20

[jobs]
format = '[$symbol$number]($style)'

[nix_shell]
impure_msg = "i"
pure_msg = "p"
symbol = "❄️"
format = '\[[$symbol$state]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

# Cloud
[kubernetes]
disabled = false
format = '\[[$symbol$context]($style)\]'
symbol = "󱃾 "

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[azure]
disabled = false
format = '\[[$symbol($subscription)]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
